import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="bg-white">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen items-center w-screen justify-center bg-white grid grid-cols-6 text-black`}
      >
        <div className="border-r w-full h-full border-black p-4 flex flex-col items-start justify-start gap-8 bg-white text-black">
          <Link href="/" className="text-2xl">
            Components
          </Link>
          <div className="w-full flex flex-col gap-2 items-start justify-start">
            <Link
              href="/header"
              className="w-full border-b hover:bg-black/10 cursor-pointer"
            >
              Header
            </Link>
            <Link
              href="/button"
              className="w-full border-b hover:bg-black/10 cursor-pointer"
            >
              Button
            </Link>
            <Link
              href="/sidebar"
              className="w-full border-b hover:bg-black/10 cursor-pointer"
            >
              Sidebar
            </Link>
          </div>
        </div>
        <div className="col-span-5 bg-white w-full h-full flex items-start justify-start pb-4 px-8 text-black pt-20">
          {children}
        </div>
      </body>
    </html>
  );
}
